import { Patient, Medicine } from '@/types';

export const mockMedicines: Medicine[] = [
  // Analgesics & NSAIDs (Ağrı Kesiciler)
  { id: '1', name: 'Aspirin', dosage: '100mg', frequency: 'Günde 1 kez' },
  { id: '2', name: 'Paracetamol', dosage: '500mg', frequency: 'Günde 3 kez' },
  { id: '3', name: 'Ibuprofen', dosage: '400mg', frequency: 'Günde 3 kez' },
  { id: '4', name: 'Naproxen', dosage: '550mg', frequency: 'Günde 2 kez' },
  { id: '5', name: 'Diclofenac', dosage: '50mg', frequency: 'Günde 2 kez' },
  { id: '6', name: 'Celecoxib', dosage: '200mg', frequency: 'Günde 2 kez' },
  { id: '7', name: 'Meloxicam', dosage: '15mg', frequency: 'Günde 1 kez' },
  { id: '8', name: 'Tramadol', dosage: '50mg', frequency: 'Günde 3 kez' },
  { id: '9', name: 'Codeine', dosage: '30mg', frequency: 'Günde 3 kez' },

  // Antibiotics (Antibiyotikler)
  { id: '10', name: 'Amoxicillin', dosage: '500mg', frequency: 'Günde 3 kez' },
  { id: '11', name: 'Azithromycin', dosage: '500mg', frequency: 'Günde 1 kez' },
  { id: '12', name: 'Ciprofloxacin', dosage: '500mg', frequency: 'Günde 2 kez' },
  { id: '13', name: 'Levofloxacin', dosage: '500mg', frequency: 'Günde 1 kez' },
  { id: '14', name: 'Cephalexin', dosage: '500mg', frequency: 'Günde 4 kez' },
  { id: '15', name: 'Clarithromycin', dosage: '500mg', frequency: 'Günde 2 kez' },
  { id: '16', name: 'Doxycycline', dosage: '100mg', frequency: 'Günde 2 kez' },
  { id: '17', name: 'Metronidazole', dosage: '500mg', frequency: 'Günde 3 kez' },
  { id: '18', name: 'Trimethoprim', dosage: '200mg', frequency: 'Günde 2 kez' },
  { id: '19', name: 'Fosfomycin', dosage: '3g', frequency: 'Tek doz' },
  { id: '101', name: 'Chloramphenicol', dosage: '250mg', frequency: 'Günde 4 kez' },
  { id: '102', name: 'Rifampisin', dosage: '600mg', frequency: 'Günde 1 kez' },

  // Cardiovascular (Kardiyovasküler)
  { id: '20', name: 'Atorvastatin', dosage: '20mg', frequency: 'Günde 1 kez' },
  { id: '21', name: 'Rosuvastatin', dosage: '10mg', frequency: 'Günde 1 kez' },
  { id: '22', name: 'Simvastatin', dosage: '40mg', frequency: 'Günde 1 kez' },
  { id: '23', name: 'Amlodipine', dosage: '5mg', frequency: 'Günde 1 kez' },
  { id: '24', name: 'Metoprolol', dosage: '50mg', frequency: 'Günde 2 kez' },
  { id: '25', name: 'Atenolol', dosage: '50mg', frequency: 'Günde 1 kez' },
  { id: '26', name: 'Ramipril', dosage: '5mg', frequency: 'Günde 1 kez' },
  { id: '27', name: 'Lisinopril', dosage: '10mg', frequency: 'Günde 1 kez' },
  { id: '28', name: 'Losartan', dosage: '50mg', frequency: 'Günde 1 kez' },
  { id: '29', name: 'Valsartan', dosage: '160mg', frequency: 'Günde 1 kez' },
  { id: '30', name: 'Clopidogrel', dosage: '75mg', frequency: 'Günde 1 kez' },
  { id: '31', name: 'Warfarin', dosage: '5mg', frequency: 'Günde 1 kez' },
  { id: '32', name: 'Rivaroxaban', dosage: '20mg', frequency: 'Günde 1 kez' },
  { id: '33', name: 'Apixaban', dosage: '5mg', frequency: 'Günde 2 kez' },
  { id: '34', name: 'Furosemide', dosage: '40mg', frequency: 'Günde 1 kez' },
  { id: '35', name: 'Spironolactone', dosage: '25mg', frequency: 'Günde 1 kez' },
  { id: '36', name: 'Digoxin', dosage: '0.25mg', frequency: 'Günde 1 kez' },
  { id: '37', name: 'Diltiazem', dosage: '60mg', frequency: 'Günde 3 kez' },
  { id: '38', name: 'Nebivolol', dosage: '5mg', frequency: 'Günde 1 kez' },

  // Antidiabetics (Antidiyabetikler)
  { id: '39', name: 'Metformin', dosage: '1000mg', frequency: 'Günde 2 kez' },
  { id: '40', name: 'Glipizide', dosage: '5mg', frequency: 'Günde 2 kez' },
  { id: '41', name: 'Gliclazide', dosage: '60mg', frequency: 'Günde 1 kez' },
  { id: '42', name: 'Sitagliptin', dosage: '100mg', frequency: 'Günde 1 kez' },
  { id: '43', name: 'Empagliflozin', dosage: '10mg', frequency: 'Günde 1 kez' },
  { id: '44', name: 'Liraglutide', dosage: '1.2mg', frequency: 'Günde 1 kez (enjeksiyon)' },
  { id: '45', name: 'Insulin Glargine', dosage: '20 Unite', frequency: 'Günde 1 kez' },
  { id: '46', name: 'Insulin Lispro', dosage: '10 Unite', frequency: 'Yemeklerden önce' },

  // Gastrointestinal (Mide-Bağırsak)
  { id: '47', name: 'Omeprazole', dosage: '20mg', frequency: 'Günde 1 kez' },
  { id: '48', name: 'Esomeprazole', dosage: '40mg', frequency: 'Günde 1 kez' },
  { id: '49', name: 'Lansoprazole', dosage: '30mg', frequency: 'Günde 1 kez' },
  { id: '50', name: 'Pantoprazole', dosage: '40mg', frequency: 'Günde 1 kez' },
  { id: '51', name: 'Ranitidine', dosage: '150mg', frequency: 'Günde 2 kez' },
  { id: '52', name: 'Metoclopramide', dosage: '10mg', frequency: 'Günde 3 kez' },
  { id: '53', name: 'Ondansetron', dosage: '8mg', frequency: 'Günde 2 kez' },
  { id: '54', name: 'Lactulose', dosage: '15ml', frequency: 'Günde 2 kez' },
  { id: '55', name: 'Loperamide', dosage: '2mg', frequency: 'Gerektiğinde' },

  // Psychiatric & Neurological (Psikiyatri ve Nöroloji)
  { id: '56', name: 'Sertraline', dosage: '50mg', frequency: 'Günde 1 kez' },
  { id: '57', name: 'Fluoxetine', dosage: '20mg', frequency: 'Günde 1 kez' },
  { id: '58', name: 'Escitalopram', dosage: '10mg', frequency: 'Günde 1 kez' },
  { id: '59', name: 'Venlafaxine', dosage: '75mg', frequency: 'Günde 1 kez' },
  { id: '60', name: 'Duloxetine', dosage: '60mg', frequency: 'Günde 1 kez' },
  { id: '61', name: 'Alprazolam', dosage: '0.5mg', frequency: 'Gerektiğinde' },
  { id: '62', name: 'Lorazepam', dosage: '1mg', frequency: 'Gerektiğinde' },
  { id: '63', name: 'Diazepam', dosage: '5mg', frequency: 'Günde 2 kez' },
  { id: '64', name: 'Zolpidem', dosage: '10mg', frequency: 'Gece yatarken' },
  { id: '65', name: 'Pregabalin', dosage: '75mg', frequency: 'Günde 2 kez' },
  { id: '66', name: 'Gabapentin', dosage: '300mg', frequency: 'Günde 3 kez' },
  { id: '67', name: 'Methylphenidate', dosage: '18mg', frequency: 'Günde 1 kez' },
  { id: '68', name: 'Quetiapine', dosage: '100mg', frequency: 'Gece yatarken' },
  { id: '69', name: 'Risperidone', dosage: '2mg', frequency: 'Günde 2 kez' },

  // Respiratory & Allergy (Solunum ve Alerji)
  { id: '70', name: 'Salbutamol', dosage: '2 puf', frequency: 'Gerektiğinde' },
  { id: '71', name: 'Budesonide', dosage: '200mcg', frequency: 'Günde 2 kez' },
  { id: '72', name: 'Montelukast', dosage: '10mg', frequency: 'Günde 1 kez' },
  { id: '73', name: 'Cetirizine', dosage: '10mg', frequency: 'Günde 1 kez' },
  { id: '74', name: 'Loratadine', dosage: '10mg', frequency: 'Günde 1 kez' },
  { id: '75', name: 'Desloratadine', dosage: '5mg', frequency: 'Günde 1 kez' },
  { id: '76', name: 'Mometasone', dosage: '1 puf', frequency: 'Günde 1 kez (nazal)' },

  // Vitamins & Supplements (Vitaminler ve Takviyeler)
  { id: '77', name: 'Vitamin D3', dosage: '1000 IU', frequency: 'Günde 1 kez' },
  { id: '78', name: 'Vitamin B12', dosage: '1000mcg', frequency: 'Günde 1 kez' },
  { id: '79', name: 'Folic Acid', dosage: '5mg', frequency: 'Günde 1 kez' },
  { id: '80', name: 'Calcium Carbonate', dosage: '500mg', frequency: 'Günde 2 kez' },
  { id: '81', name: 'Iron Sulfate', dosage: '325mg', frequency: 'Günde 1 kez' },
  { id: '82', name: 'Magnesium', dosage: '400mg', frequency: 'Günde 1 kez' },
  { id: '83', name: 'Omega-3', dosage: '1000mg', frequency: 'Günde 1 kez' },
  { id: '84', name: 'Multivitamin', dosage: '1 tablet', frequency: 'Günde 1 kez' },

  // Others (Diğerleri)
  { id: '85', name: 'Levothyroxine', dosage: '100mcg', frequency: 'Günde 1 kez' },
  { id: '86', name: 'Sildenafil', dosage: '50mg', frequency: 'Aktiviteden önce' },
  { id: '87', name: 'Tadalafil', dosage: '20mg', frequency: 'Aktiviteden önce' },
  { id: '88', name: 'Tamsulosin', dosage: '0.4mg', frequency: 'Günde 1 kez' },
  { id: '89', name: 'Finasteride', dosage: '5mg', frequency: 'Günde 1 kez' },
  { id: '90', name: 'Acyclovir', dosage: '400mg', frequency: 'Günde 5 kez' },
  { id: '91', name: 'Valacyclovir', dosage: '1000mg', frequency: 'Günde 2 kez' },
  { id: '92', name: 'Oseltamivir', dosage: '75mg', frequency: 'Günde 2 kez' },
  { id: '93', name: 'Prednisone', dosage: '20mg', frequency: 'Günde 1 kez' },
  { id: '94', name: 'Dexamethasone', dosage: '4mg', frequency: 'Günde 1 kez' },
  { id: '95', name: 'Allopurinol', dosage: '300mg', frequency: 'Günde 1 kez' },
  { id: '96', name: 'Colchicine', dosage: '0.6mg', frequency: 'Günde 2 kez' },
  { id: '97', name: 'Bisoprolol', dosage: '5mg', frequency: 'Günde 1 kez' },
  { id: '98', name: 'Carvedilol', dosage: '25mg', frequency: 'Günde 2 kez' },
  { id: '99', name: 'Propranolol', dosage: '40mg', frequency: 'Günde 3 kez' },
  { id: '100', name: 'Hydrochlorothiazide', dosage: '25mg', frequency: 'Günde 1 kez' },
];

export const mockPatients: Patient[] = [
  {
    id: '1',
    name: 'Ahmet Yılmaz',
    age: 45,
    gender: 'male',
    conditions: ['Hipertansiyon', 'Diyabet'],
    currentMedications: [
      { id: '39', name: 'Metformin', dosage: '1000mg', frequency: 'Günde 2 kez' },
      { id: '26', name: 'Ramipril', dosage: '5mg', frequency: 'Günde 1 kez' },
    ],
    prescriptions: [],
  },
  {
    id: '2',
    name: 'Ayşe Kaya',
    age: 32,
    gender: 'female',
    conditions: ['Migren'],
    currentMedications: [
      { id: '2', name: 'Paracetamol', dosage: '500mg', frequency: 'Günde 3 kez' },
    ],
    prescriptions: [],
  },
  {
    id: '3',
    name: 'Mehmet Demir',
    age: 58,
    gender: 'male',
    conditions: ['Kalp Hastalığı', 'Yüksek Kolesterol'],
    currentMedications: [
      { id: '1', name: 'Aspirin', dosage: '100mg', frequency: 'Günde 1 kez' },
      { id: '20', name: 'Atorvastatin', dosage: '20mg', frequency: 'Günde 1 kez' },
    ],
    prescriptions: [],
  },
  {
    id: '4',
    name: 'Fatma Öztürk',
    age: 67,
    gender: 'female',
    conditions: ['Hipotiroidi', 'Hipertansiyon', 'Osteoporoz'],
    currentMedications: [
      { id: '85', name: 'Levothyroxine', dosage: '100mcg', frequency: 'Günde 1 kez' },
      { id: '23', name: 'Amlodipine', dosage: '5mg', frequency: 'Günde 1 kez' },
      { id: '80', name: 'Calcium Carbonate', dosage: '500mg', frequency: 'Günde 2 kez' },
    ],
    prescriptions: [],
  },
];
